# Generated by Django 2.1.2 on 2018-12-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_handling', '0004_auto_20180628_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
